# Copy of https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/conda/conda.plugin.zsh
# Only with mamba instead of conda, and with some additional aliases
alias cna='mamba activate'
alias cnab='mamba activate base'
alias cncf='mamba env create -f'
alias cncn='mamba create -y -n'
alias cnconf='mamba config'
alias cncp='mamba create -y -p'
alias cncr='mamba create -n'
alias cncss='mamba config --show-source'
alias cnde='mamba deactivate'
alias cnel='mamba env list'
alias cni='mamba install'
alias cniy='mamba install -y'
alias cnl='mamba list'
alias cnle='mamba list --export'
alias cnles='mamba list --explicit > spec-file.txt'
alias cnr='mamba remove'
alias cnrn='mamba remove -y --all -n'
alias cnrp='mamba remove -y --all -p'
alias cnry='mamba remove -y'
alias cnsr='mamba search'
alias cnu='mamba update'
alias cnua='mamba update --all'
alias cnuc='mamba update mamba'